Repository knowledgesystems/cmo-pipelines, pull requests merged in 2020-09, with the labels that each got.

#783 upgrade oncokb-annotator script to python3
  import-scripts/oncokb-annotator.sh
Labels: bug

#784 Prune git lfs cache after cleanup
  import-scripts/datasource-repo-cleanup.sh
Labels: skip-integration-tests

#786 Detects Non-ASCII characters
  import-scripts/clinicalfile_utils.py
  import-scripts/generate_cdd_attribute_tsv.py
  import-scripts/test_generate_cdd_attribute_tsv.py
Labels: enhancement, import-scripts
