Repository knowledgesystems/cmo-pipelines, pull requests merged in 2020-04, with the labels that each got.

#707 Add a slack warning when import jobs are stalled
  import-scripts/monitor-stalled-jobs.sh
  import-scripts/mycrontab
Labels: enhancement, import-scripts

#705 insulate oncokb-annotator from dmp runs
  import-scripts/automation-environment.sh
  import-scripts/create_web_directory_index_file.sh
  import-scripts/oncokb-annotator.sh
  import-scripts/set-data-source-environment-vars.sh
Labels: enhancement, import-scripts

#709 update jitpack hash for GNAP to master (04/15/2020)
  cvr/pom.xml
Labels: skip-integration-tests

#710 Reintroduce Re-annotation Flag
  cvr/pom.xml
  cvr/src/main/java/org/cbioportal/cmo/pipelines/cvr/mutation/CVRMutationDataReader.java
  cvr/src/main/java/org/cbioportal/cmo/pipelines/cvr/mutation/CVRUnfilteredMutationDataReader.java
  cvr/src/main/java/org/cbioportal/cmo/pipelines/cvr/mutation/GMLMutationDataReader.java
Labels: skip-integration-tests

#712 Add headers for different types of jobs in our crontab
  import-scripts/mycrontab
Labels: skip-integration-tests

#706 Genie support tools
  import-scripts/annotation_suite/README.md
  import-scripts/annotation_suite/annotation_suite_wrapper.sh
  import-scripts/annotation_suite/merge_mafs.py
  import-scripts/annotation_suite/standardize_mutation_data.py
Labels: skip-integration-tests

#717 Add not logical operator for SSL cert file check
  import-scripts/annotation_suite/annotation_suite_wrapper.sh
Labels: skip-integration-tests

#723 deleted genie annotation-suite (relocated)
  import-scripts/annotation_suite/README.md
  import-scripts/annotation_suite/annotation_suite_wrapper.sh
  import-scripts/annotation_suite/merge_mafs.py
  import-scripts/annotation_suite/standardize_mutation_data.py
Labels: skip-integration-tests

#724 option to reannotate all mutations with oncokb
  import-scripts/mycrontab
  import-scripts/oncokb-annotator.sh
Labels: enhancement
