Repository knowledgesystems/cmo-pipelines, pull requests merged in 2020-05, with the labels that each got.

#726 reannotate bug fix and add zipping
  import-scripts/oncokb-annotator.sh
Labels: bug, skip-integration-tests

#722 Import HGNC Script
  import-scripts/import-hgnc.sh
Labels: do not merge, enhancement, skip-integration-tests

#727 add umask so anyone can clean tmp dir
  import-scripts/import-hgnc.sh
Labels: bug, skip-integration-tests

#728 add chmod of PORTAL_DATA_HOME for others
  import-scripts/import-hgnc.sh
Labels: bug, skip-integration-tests

#725 option to reannotate all mutations with oncokb
  import-scripts/oncokb-annotator.sh
Labels: bug, skip-integration-tests

#735 Disable the fetching of datahub for hgnc importer
  import-scripts/import-hgnc.sh
Labels: enhancement, skip-integration-tests

#736 Use somatic session id for master list endpoint even in gml mode
  cvr/src/main/java/org/cbioportal/cmo/pipelines/CVRPipeline.java
  cvr/src/main/java/org/cbioportal/cmo/pipelines/cvr/samplelist/CvrSampleListsTasklet.java
Labels: cvr

#737 add data usage agreement to oncokb index.html
  import-scripts/create_web_directory_index_file.sh
Labels: enhancement
